apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collector-pvc
  namespace: system
spec:
  storageClassName: my-nfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi